добавлена функция сортировки строк
js-tasks-ru/js-20230117_galina9 pull request #2
Opened 2023-01-22 09:24 UTC by GalinaGorbel

Задача 02_01 - sort-strings

2023-01-22 09:25 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-23 07:15 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-01-23 07:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-01-23 07:20 UTC, GalinaGorbel commented
Я поняла, что commit можно делать для каждой задачи, а pull request один )

2023-01-23 08:50 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const sortArr = arr.map((item) => item.trim());
для копирования массива следует сделать вот так:
```
const copy = [...arr];
```

2023-01-23 08:50 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    sortArr.sort((a, b) => (a.trim()).localeCompare((b.trim()), ['ru', 'en']));
следует устранить дубликаты коды в строках 11 и 14

2023-01-23 08:51 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return sortArr.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2023-01-23 08:51 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.spec.js
> +      'Детский велосипед Lexus Trike Racer Trike  ',
зачем тут пробел в тестовых данных?

2023-01-23 08:51 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.fromEntries(Object.entries(obj).filter(([key]) => fields.includes(key)));
👍 good

2023-01-23 08:51 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  return Object.fromEntries(Object.entries(obj).filter(([key]) => !fields.includes(key)));
👍 good

2023-01-23 08:51 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2023-01-23 10:33 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-01-24 09:10 UTC, dosandk approved these changes
👍 good

2023-01-24 09:10 UTC, merged